FROM golang:1.18.1-alpine3.15 as builder
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN apk update && apk upgrade && \
  apk add --no-cache ca-certificates git curl

RUN mkdir /api
WORKDIR /api
ADD . /api
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN swag init
RUN go mod download
RUN go build -o api

FROM alpine:3.15.0

RUN apk update && apk upgrade && \
  apk add --no-cache ca-certificates tzdata

COPY --from=builder /api/api .
COPY --from=builder /api/docs /docs

ADD /configs /configs
ADD /templates /templates
ADD /json /json

ENV TZ=Asia/Bangkok

ENTRYPOINT ["/api", "-environment", "dev"]

EXPOSE 8000
